# Generated by Django 2.2.10 on 2021-11-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='city',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
