# Generated by Django 2.2.10 on 2021-11-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211106_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='region',
        ),
    ]
