# Generated by Django 2.2.10 on 2021-11-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bookmark_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
