# Generated by Django 2.2.10 on 2021-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211106_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarks',
            old_name='cases',
            new_name='confirmed',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='deaths',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
