# Generated by Django 2.2.10 on 2021-11-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211107_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='confirmed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='deaths',
            field=models.IntegerField(),
        ),
    ]
