# Generated by Django 2.2.10 on 2021-11-10 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211110_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.today, editable=False),
        ),
    ]
